# Booking Cancelation Prediction

### Importing Libraries

In [3]:
import pandas as pd
import numpy as np

### Loading Dataset

In [6]:
data = pd.read_csv('hotel_bookings.csv')

### Data Analysis

In [9]:
data.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

### Categorical Data

In [14]:
cat = [i for i in data.columns if data[i].dtype =='O']

In [16]:
len(cat)

12

In [18]:
cat

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status',
 'reservation_status_date']

In [20]:
pd.set_option('display.max_columns',36)

In [22]:
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [24]:
cat = ['hotel','arrival_date_year','arrival_date_month','meal','market_segment','distribution_channel','is_repeated_guest','reserved_room_type',
      'assigned_room_type','agent','company','customer_type','reservation_status']

In [26]:
len(cat)

13

In [28]:
for i in cat:
    if i in data.columns:
        data[i]=data[i].astype(str)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  object
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  object
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           119390 non-null  object
 24  company                         119390 non-null  object
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(2), int64(14), object(16)
memory usage: 29.1+ MB

### Transposing the data for data analysing.

In [34]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
is_canceled,119390.0,0.370416,0.482918,0.00,0.00,0.000,1.0,1.0
lead_time,119390.0,104.011416,106.863097,0.00,18.00,69.000,160.0,737.0
arrival_date_week_number,119390.0,27.165173,13.605138,1.00,16.00,28.000,38.0,53.0
arrival_date_day_of_month,119390.0,15.798241,8.780829,1.00,8.00,16.000,23.0,31.0
stays_in_weekend_nights,119390.0,0.927599,0.998613,0.00,0.00,1.000,2.0,19.0
stays_in_week_nights,119390.0,2.500302,1.908286,0.00,1.00,2.000,3.0,50.0
adults,119390.0,1.856403,0.579261,0.00,2.00,2.000,2.0,55.0
children,119386.0,0.103890,0.398561,0.00,0.00,0.000,0.0,10.0
babies,119390.0,0.007949,0.097436,0.00,0.00,0.000,0.0,10.0
previous_cancellations,119390.0,0.087118,0.844336,0.00,0.00,0.000,0.0,26.0
previous_bookings_not_canceled,119390.0,0.137097,1.497437,0.00,0.00,0.000,0.0,72.0
booking_changes,119390.0,0.221124,0.652306,0.00,0.00,0.000,0.0,21.0
days_in_waiting_list,119390.0,2.321149,17.594721,0.00,0.00,0.000,0.0,391.0
adr,119390.0,101.831122,50.535790,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,0.062518,0.245291,0.00,0.00,0.000,0.0,8.0
total_of_special_requests,119390.0,0.571363,0.792798,0.00,0.00,0.000,1.0,5.0

In [36]:
data.describe(include='object').T

                          count unique         top    freq
hotel                    119390      2  City Hotel   79330
arrival_date_year        119390      3        2016   56707
arrival_date_month       119390     12      August   13877
meal                     119390      5          BB   92310
country                  118902    177         PRT   48590
market_segment           119390      8   Online TA   56477
distribution_channel     119390      5       TA/TO   97870
is_repeated_guest        119390      2           0  115580
reserved_room_type       119390     10           A   85994
assigned_room_type       119390     12           A   74053
deposit_type             119390      3  No Deposit  104641
agent                    119390    334         9.0   31961
company                  119390    353         nan  112593
customer_type            119390      4   Transient   89613
reservation_status       119390      3   Check-Out   75166
reservation_status_date  119390    926  2015-10-21    1461

### Removing columns in order to escape from data leakage

In [39]:
for i in['reservation_status','reservation_status_date','assigned_room_type']:
    data.drop(i,inplace=True,axis=1)

In [41]:
data

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,3,No Deposit,nan,nan,0,Transient,0.00,0,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,4,No Deposit,nan,nan,0,Transient,0.00,0,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,0,No Deposit,nan,nan,0,Transient,75.00,0,0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,0,No Deposit,304.0,nan,0,Transient,75.00,0,0
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,0,No Deposit,240.0,nan,0,Transient,98.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,394.0,nan,0,Transient,96.14,0,0
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,0,No Deposit,9.0,nan,0,Transient,225.43,0,2
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,0,No Deposit,9.0,nan,0,Transient,157.71,0,4
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,0,No Deposit,89.0,nan,0,Transient,104.40,0,0
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,0,No Deposit,9.0,nan,0,Transient,151.20,0,2

### Removing irrelevant column

In [44]:
data.drop('arrival_date_year',axis=1,inplace=True)

### Removing high unique values

In [47]:
data.describe(include='object').T

                       count unique         top    freq
hotel                 119390      2  City Hotel   79330
arrival_date_month    119390     12      August   13877
meal                  119390      5          BB   92310
country               118902    177         PRT   48590
market_segment        119390      8   Online TA   56477
distribution_channel  119390      5       TA/TO   97870
is_repeated_guest     119390      2           0  115580
reserved_room_type    119390     10           A   85994
deposit_type          119390      3  No Deposit  104641
agent                 119390    334         9.0   31961
company               119390    353         nan  112593
customer_type         119390      4   Transient   89613

In [49]:
high_cat = ['country','agent','company']

In [51]:
uniques = data[high_cat].nunique()

In [53]:
uniques

country    177
agent      334
company    353
dtype: int64

In [55]:
missing = data[high_cat].isna().sum()

In [57]:
missing

country    488
agent        0
company      0
dtype: int64

In [59]:
for i in high_cat:
    data.drop(i,axis=1,inplace=True)

In [61]:
data

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,July,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,3,No Deposit,0,Transient,0.00,0,0
1,Resort Hotel,0,737,July,27,1,0,0,2,0.0,0,BB,Direct,Direct,0,0,0,C,4,No Deposit,0,Transient,0.00,0,0
2,Resort Hotel,0,7,July,27,1,0,1,1,0.0,0,BB,Direct,Direct,0,0,0,A,0,No Deposit,0,Transient,75.00,0,0
3,Resort Hotel,0,13,July,27,1,0,1,1,0.0,0,BB,Corporate,Corporate,0,0,0,A,0,No Deposit,0,Transient,75.00,0,0
4,Resort Hotel,0,14,July,27,1,0,2,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,98.00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,August,35,30,2,5,2,0.0,0,BB,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,0,Transient,96.14,0,0
119386,City Hotel,0,102,August,35,31,2,5,3,0.0,0,BB,Online TA,TA/TO,0,0,0,E,0,No Deposit,0,Transient,225.43,0,2
119387,City Hotel,0,34,August,35,31,2,5,2,0.0,0,BB,Online TA,TA/TO,0,0,0,D,0,No Deposit,0,Transient,157.71,0,4
119388,City Hotel,0,109,August,35,31,2,5,2,0.0,0,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,104.40,0,0
119389,City Hotel,0,205,August,35,29,2,7,2,0.0,0,HB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,151.20,0,2

### Checking null values

In [64]:
data.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          4
babies                            0
meal                              0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
dtype: int64

In [66]:
data['children'].value_counts()

children
0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: count, dtype: int64

In [68]:
data['children'] = data['children'].fillna(0)

### Handling noise data

In [71]:
noise = {'adr':data[data['adr']<0],
         'adults':data[data['adults']==0],
         'children':data[data['children']==10],
         'babies':data[data['babies']==10]}

In [73]:
noise_data = {i:len(j) for i,j in noise.items()}

In [75]:
noise_data

{'adr': 1, 'adults': 403, 'children': 1, 'babies': 1}

In [77]:
for i in noise.keys():
    data.drop(i,axis=1,inplace=True)

In [79]:
data

,hotel,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,meal,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,July,27,1,0,0,BB,Direct,Direct,0,0,0,C,3,No Deposit,0,Transient,0,0
1,Resort Hotel,0,737,July,27,1,0,0,BB,Direct,Direct,0,0,0,C,4,No Deposit,0,Transient,0,0
2,Resort Hotel,0,7,July,27,1,0,1,BB,Direct,Direct,0,0,0,A,0,No Deposit,0,Transient,0,0
3,Resort Hotel,0,13,July,27,1,0,1,BB,Corporate,Corporate,0,0,0,A,0,No Deposit,0,Transient,0,0
4,Resort Hotel,0,14,July,27,1,0,2,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,August,35,30,2,5,BB,Offline TA/TO,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,0
119386,City Hotel,0,102,August,35,31,2,5,BB,Online TA,TA/TO,0,0,0,E,0,No Deposit,0,Transient,0,2
119387,City Hotel,0,34,August,35,31,2,5,BB,Online TA,TA/TO,0,0,0,D,0,No Deposit,0,Transient,0,4
119388,City Hotel,0,109,August,35,31,2,5,BB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,0
119389,City Hotel,0,205,August,35,29,2,7,HB,Online TA,TA/TO,0,0,0,A,0,No Deposit,0,Transient,0,2

### Implemeting one hot encoding

In [82]:
cat = [i for i in data.columns if data[i].dtype == 'O']
one_hot = [i for i in cat if i!='arrival_date_month']

In [84]:
data =pd.get_dummies(data,columns=one_hot,dtype=int)

In [86]:
data

,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,required_car_parking_spaces,total_of_special_requests,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,...,is_repeated_guest_1,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,reserved_room_type_P,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,July,27,1,0,0,0,0,3,0,0,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
1,0,737,July,27,1,0,0,0,0,4,0,0,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2,0,7,July,27,1,0,1,0,0,0,0,0,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,0,13,July,27,1,0,1,0,0,0,0,0,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,0,14,July,27,1,0,2,0,0,0,0,0,1,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,August,35,30,2,5,0,0,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,0,102,August,35,31,2,5,0,0,0,0,0,2,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119387,0,34,August,35,31,2,5,0,0,0,0,0,4,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
119388,0,109,August,35,31,2,5,0,0,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,0,205,August,35,29,2,7,0,0,0,0,0,2,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 52 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   is_canceled                     119390 non-null  int64
 1   lead_time                       119390 non-null  int64
 2   arrival_date_month              119390 non-null  object
 3   arrival_date_week_number        119390 non-null  int64
 4   arrival_date_day_of_month       119390 non-null  int64
 5   stays_in_weekend_nights         119390 non-null  int64
 6   stays_in_week_nights            119390 non-null  int64
 7   previous_cancellations          119390 non-null  int64
 8   previous_bookings_not_canceled  119390 non-null  int64
 9   booking_changes                 119390 non-null  int64
 10  days_in_waiting_list            119390 non-null  int64
 11  required_car_parking_spaces     119390 non-null  int64
 12  total_of_special_requests       119390 non-null  int64
 13  hotel_City Hotel                119390 non-null  int64
 14  hotel_Resort Hotel              119390 non-null  int64
 15  meal_BB                         119390 non-null  int64
 16  meal_FB                         119390 non-null  int64
 17  meal_HB                         119390 non-null  int64
 18  meal_SC                         119390 non-null  int64
 19  meal_Undefined                  119390 non-null  int64
 20  market_segment_Aviation         119390 non-null  int64
 21  market_segment_Complementary    119390 non-null  int64
 22  market_segment_Corporate        119390 non-null  int64
 23  market_segment_Direct           119390 non-null  int64
 24  market_segment_Groups           119390 non-null  int64
 25  market_segment_Offline TA/TO    119390 non-null  int64
 26  market_segment_Online TA        119390 non-null  int64
 27  market_segment_Undefined        119390 non-null  int64
 28  distribution_channel_Corporate  119390 non-null  int64
 29  distribution_channel_Direct     119390 non-null  int64
 30  distribution_channel_GDS        119390 non-null  int64
 31  distribution_channel_TA/TO      119390 non-null  int64
 32  distribution_channel_Undefined  119390 non-null  int64
 33  is_repeated_guest_0             119390 non-null  int64
 34  is_repeated_guest_1             119390 non-null  int64
 35  reserved_room_type_A            119390 non-null  int64
 36  reserved_room_type_B            119390 non-null  int64
 37  reserved_room_type_C            119390 non-null  int64
 38  reserved_room_type_D            119390 non-null  int64
 39  reserved_room_type_E            119390 non-null  int64
 40  reserved_room_type_F            119390 non-null  int64
 41  reserved_room_type_G            119390 non-null  int64
 42  reserved_room_type_H            119390 non-null  int64
 43  reserved_room_type_L            119390 non-null  int64
 44  reserved_room_type_P            119390 non-null  int64
 45  deposit_type_No Deposit         119390 non-null  int64
 46  deposit_type_Non Refund         119390 non-null  int64
 47  deposit_type_Refundable         119390 non-null  int64
 48  customer_type_Contract          119390 non-null  int64
 49  customer_type_Group             119390 non-null  int64
 50  customer_type_Transient         119390 non-null  int64
 51  customer_type_Transient-Party   119390 non-null  int64
dtypes: int64(51), object(1)
memory usage: 47.4+ MB

### Using months concept

In [91]:
data['arrival_date_month'].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [93]:
months = ['January', 'February', 'March', 'April', 'May', 'June','July', 'August', 'September', 'October', 'November', 'December']

In [95]:
data['arrival_date_month']=data['arrival_date_month'].apply(lambda x:months.index(x))

In [97]:
data

,is_canceled,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,required_car_parking_spaces,total_of_special_requests,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,...,is_repeated_guest_1,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,reserved_room_type_P,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,0,342,6,27,1,0,0,0,0,3,0,0,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
1,0,737,6,27,1,0,0,0,0,4,0,0,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2,0,7,6,27,1,0,1,0,0,0,0,0,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,0,13,6,27,1,0,1,0,0,0,0,0,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,0,14,6,27,1,0,2,0,0,0,0,0,1,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,7,35,30,2,5,0,0,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,0,102,7,35,31,2,5,0,0,0,0,0,2,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119387,0,34,7,35,31,2,5,0,0,0,0,0,4,1,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
119388,0,109,7,35,31,2,5,0,0,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,0,205,7,35,29,2,7,0,0,0,0,0,2,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

### Finding out the data balance

In [100]:
bal = data['is_canceled'].value_counts(normalize=True)*100

In [102]:
bal

is_canceled
0    62.958372
1    37.041628
Name: proportion, dtype: float64

### Model Applying

In [105]:
X = data.drop('is_canceled',axis=1)
y = data['is_canceled']

In [107]:
X

,lead_time,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,required_car_parking_spaces,total_of_special_requests,hotel_City Hotel,hotel_Resort Hotel,meal_BB,meal_FB,meal_HB,meal_SC,...,is_repeated_guest_1,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,reserved_room_type_P,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party
0,342,6,27,1,0,0,0,0,3,0,0,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
1,737,6,27,1,0,0,0,0,4,0,0,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0
2,7,6,27,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
3,13,6,27,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
4,14,6,27,1,0,2,0,0,0,0,0,1,0,1,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,23,7,35,30,2,5,0,0,0,0,0,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119386,102,7,35,31,2,5,0,0,0,0,0,2,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0
119387,34,7,35,31,2,5,0,0,0,0,0,4,1,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0
119388,109,7,35,31,2,5,0,0,0,0,0,0,1,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0
119389,205,7,35,29,2,7,0,0,0,0,0,2,1,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0

In [109]:
y

0         0
1         0
2         0
3         0
4         0
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: is_canceled, Length: 119390, dtype: int64

### Train test split

In [112]:
from sklearn.model_selection import train_test_split

In [114]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

### Implementation algorithms

In [117]:
from sklearn.model_selection import GridSearchCV,StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

In [119]:
def tuning(cls,parameter,X_train,y_train):
    cv = StratifiedKFold(n_splits=5,shuffle=True)
    cls_grid = GridSearchCV(cls,parameter,cv=cv,scoring='f1',n_jobs=-1)
    cls_grid.fit(X_train,y_train)
    best_hp = cls_grid.best_params_
    return cls_grid.best_estimator_,best_hp

In [121]:
dt = DecisionTreeClassifier()

In [123]:
dt_parameter_grid = {
    'criterion':['gini','entropy'],
    'max_depth':[12,13,14]
}

In [125]:
tuning(dt,dt_parameter_grid,X_train,y_train)

D:\Ana\Lib\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

(DecisionTreeClassifier(max_depth=14), {'criterion': 'gini', 'max_depth': 14})

In [127]:
b_e,b_h=tuning(dt,dt_parameter_grid,X_train,y_train)

In [131]:
dt = DecisionTreeClassifier(criterion = 'gini', max_depth = 14)

In [135]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=14)

In [137]:
y_pred = dt.predict(X_test)

In [139]:
y_pred

array([1, 1, 0, ..., 0, 1, 0])

In [141]:
y_test

68137     1
54393     1
110653    0
539       0
6149      0
         ..
85754     0
77954     0
44016     0
116584    0
105347    0
Name: is_canceled, Length: 35817, dtype: int64

In [145]:
accuracy_score(y_test,y_pred)*100

82.20677331993188

In [150]:
xgb_parameter_grid = {
    'n_estimators':[250,300],
    'learning_rate':[0.01,0.001,0.1],
    'max_depth':[7,8]
}

In [152]:
xgb = XGBClassifier()

In [154]:
xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [158]:
y_pred = xgb.predict(X_test)

In [160]:
accuracy_score(y_test,y_pred)*100

83.30122567495883